version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pulse_db
    environment:
      POSTGRES_DB: pulse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulse_network
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pulse_db" ]
      interval: 5s
      timeout: 3s
      retries: 3

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pulse-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rag.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pulse_network
    depends_on:
      - db
    restart: unless-stopped


  redis-cache:
    image: redis:8.0-alpine
    container_name: redis-chat
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - pulse_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s




  # app:
  #   build: .
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  cache:
    driver: local


networks:
  pulse_network:
    driver: bridge